import os

file_path = r'C:\Users\vaska\Desktop\void-covenant\src\components\BattleFieldView.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    "getSkillNameRussian": "getSkillNameEnglish",
    "getSkillDescRussian": "getSkillDescEnglish",
    "'Жертва'": "'Sacrifice'",
    "'Вампиризм'": "'Vampirism'",
    "'Проклятие'": "'Hex'",
    "'Чума'": "'Plague'",
    "Жертва союзника: при розыгрыше уничтожает случайное дружественное существо, исцеляя Вашего Лорда на +${value} HP и навсегда усиливая свои параметры на +${Math.round(value/2)} АТК и +${value} ОЗ.": "Ally sacrifice: destroys a random friendly creature on play, healing your Lord by +${value} HP and permanently buffing stats by +${Math.round(value/2)} ATK and +${value} HP.",
    "Исцеляет эту карту на +${value} ОЗ каждый раз, когда она наносит урон противнику напротив.": "Heals this card by +${value} HP every time it deals damage to the enemy opposite.",
    "Накладывает сглаз на карту напротив, увеличивая весь следующий входящий по ней урон на +${value}.": "Hexes the opposite card, increasing all next incoming damage by +${value}.",
    "В конце каждого хода распространяет заразу, нанося -${value} ОЗ случайной живой карте врага.": "Spreads plague at the end of each turn, dealing -${value} HP to a random living enemy card.",
    "Особая способность силой ${value}.": "Special ability of power ${value}.",
    "💀 Жертвоприношение: ${placingCard?.name || 'Карта'} уничтожает ${sacrCard?.name || 'союзника'}": "💀 Sacrifice: ${placingCard?.name || 'Card'} destroys ${sacrCard?.name || 'ally'}",
    "💀 ЖЕРТВА": "💀 SACRIFICE",
    "😈 Темный Призыв: Лорд призывает ${step.card.name}": "😈 Dark Summon: Lord summons ${step.card.name}",
    "'ПРИЗЫВ'": "'SUMMON'",
    "🗡️ Дуэль: ${attackerCard?.name || 'Существо'} наносит -${step.damage} урона по ${defenderCard?.name || 'Цели'}": "🗡️ Duel: ${attackerCard?.name || 'Creature'} deals -${step.damage} damage to ${defenderCard?.name || 'Target'}",
    "💥 Прорыв: ${attackerCard?.name || 'Существо'} наносит -${step.damage} прямого урона Лорду!": "💥 Breakthrough: ${attackerCard?.name || 'Creature'} deals -${step.damage} direct damage to Lord!",
    "🤢 Чумная слизь: ${sourceCard?.name || 'Гниль'} заражает ${targetCard?.name || 'цель'} на -${step.damage} ОЗ": "🤢 Plague slime: ${sourceCard?.name || 'Rot'} infects ${targetCard?.name || 'target'} for -${step.damage} HP",
    "☠️ Разрушение: ${deadCardName || 'Существо'} разрывается в пыль!": "☠️ Destruction: ${deadCardName || 'Creature'} turns to dust!",
    "'💀 РАЗОРВАН'": "'💀 DESTROYED'",
    "Вы уверены, что хотите сбежать? Энергия не будет возвращена.": "Are you sure you want to escape? Energy will not be refunded.",
    "СБЕЖАТЬ С ПОЛЯ": "ESCAPE BATTLEFIELD",
    "— БИТВА ХОД": "— BATTLE TURN",
    "Вражеский Лорд": "Enemy Lord",
    "Здоровье:": "Health:",
    "Фаза Боя": "Battle Phase",
    "Запуск боевого дуэлянта...": "Starting combat duelist...",
    "Ход ": "Turn ",
    "СТАРТ": "START",
    "ПАУЗА": "PAUSE",
    "ШАГ ➡️": "STEP ➡️",
    "Задержка": "Delay",
    "нет навыков": "no skills",
    "Слот ": "Slot ",
    "Выбрать 📥": "Select 📥",
    "Ваш Герой": "Your Hero",
    "Призыватель Ветра": "Wind Summoner",
    "⏳ СДЕЛАТЬ ХОД БЕЗ КАРТЫ": "⏳ PLAY TURN WITHOUT CARD",
    "📥 Выберите свободный Слот на поле боя": "📥 Select an empty Slot on battlefield",
    "✕ ОТМЕНА": "✕ CANCEL",
    "🃏 ВАША РУКА": "🃏 YOUR HAND",
    "Выбрана": "Selected",
    "Выставить": "Deploy",
    "Колода пуста.": "Deck is empty.",
    "Готов": "Ready",
    "АТАКA": "ATTACK",
    "ЗДОРОВЬЕ": "HEALTH",
    "ЗАДЕРЖКА": "DELAY",
    "АКТИВНЫЕ СПОСОБНОСТИ": "ACTIVE ABILITIES",
    "У этого существа нет тёмных способностей.": "This creature has no dark abilities.",
    "АНАЛИЗАТОР СХВАТКИ": "COMBAT ANALYZER",
    "ПРАВИЛА": "RULES",
    "Наведите курсор на любую карту на столе или в руке, чтобы получить полную тактическую справку.": "Hover over any card on board or in hand to get full tactical info.",
    "Ходы ожидания атаки.": "Turns waiting to attack.",
    "Уничтожает союзника.": "Destroys an ally.",
    "📜 ЛОГ КРОВАВОЙ ДУЭЛИ": "📜 BLOODY DUEL LOG",
    "'ХОД'": "'TURN'",
    "'ПОБЕДА'": "'VICTORY'",
    "'исцелен'": "'healed'",
    "'ПОРАЖЕНИЕ'": "'DEFEAT'",
    "'пала'": "'fell'",
    "'Гибель'": "'Death'",
    "'Жертва'": "'Sacrifice'",
    "'Проклятие'": "'Hex'",
    "'Враг'": "'Enemy'",
    "ТРИУМФ НА АРЕНЕ!": "ARENA TRIUMPH!",
    "ПОБЕДА КОВЕНАНТА!": "COVENANT VICTORY!",
    "Вы одолели вражеского призывателя и заслужили славу.": "You defeated the enemy summoner and earned glory.",
    "Вы разгромили лорда бездны и очистили проклятые земли.": "You defeated the abyssal lord and cleansed the cursed lands.",
    "ПОЛУЧЕННАЯ НАГРАДА": "REWARD OBTAINED",
    "Золото": "Gold",
    "Пыль Тьмы": "Dark Dust",
    "MMR Рейтинг": "MMR Rating",
    "Осколки": "Shards",
    "Очков Тёмного Пропуска": "Dark Pass Points",
    "ЗАБРАТЬ ДОБЫЧУ И ВЫЙТИ": "CLAIM LOOT AND EXIT",
    "ВЫ ПОВЕРЖЕНЫ": "YOU ARE DEFEATED",
    "Ваш соперник оказался сильнее в этой дуэли. Настройте вашу колоду и берите реванш!": "Your opponent was stronger in this duel. Adjust your deck and take revenge!",
    "Тьма поглотила ваш разум. Улучшайте карты и пробуйте снова.": "Darkness consumed your mind. Upgrade cards and try again.",
    "ПОСЛЕДСТВИЯ БОЯ": "BATTLE CONSEQUENCES",
    "ВЕРНУТЬСЯ В ШТАБ": "RETURN TO HQ",
    "РУКОВОДСТВО ПО ТАКТИКЕ БОЯ": "COMBAT TACTICS GUIDE",
    "ЗАКРЫТЬ": "CLOSE",
    "Боевая Система": "Combat System",
    "Сражение происходит 1 на 1 на линейном поле из 5 слотов. Карты атакуют <strong>строго напротив себя</strong>.\n                    Если слот напротив пуст, весь урон идет напрямую в здоровье вражеского героя (Лорда). Цель боя — обнулить здоровье врага.": "Combat is 1v1 on a linear 5-slot board. Cards attack <strong>strictly opposite themselves</strong>.\n                    If the slot opposite is empty, all damage goes directly to enemy hero (Lord). Goal is to bring enemy health to zero.",
    "Механика Задержки": "Delay Mechanics",
    "При размещении карты на поле, она имеет показатель задержки (например, 1, 2 или 3 хода). Она не может атаковать\n                    сразу. Каждый ход таймер снижается на 1. При достижении 0 карта становится активной ⚔️ и атакует в конце каждого вашего хода.": "When placed on board, card has a delay indicator (e.g. 1, 2 or 3 turns). It cannot attack\n                    immediately. Each turn timer decreases by 1. Reaching 0 makes card active ⚔️ and attacks at the end of each your turn.",
    "Тёмные Навыки Существ": "Dark Creature Skills",
    "Жертвоприношение": "Sacrifice",
    "При розыгрыше уничтожает случайное союзное существо на вашем столе. Взамен исцеляет вашего героя на X HP,\n                        а само существо навсегда получает <strong>+(X/2) к Атаке</strong> и <strong>+X к Здоровью</strong>.": "On play, destroys a random ally on your board. In return, heals your hero by X HP,\n                        and creature permanently gets <strong>+(X/2) Attack</strong> and <strong>+X Health</strong>.",
    "Каждый раз, когда существо атакует и наносит урон другой карте, оно исцеляет себя на X единиц здоровья\n                        (но не выше своего максимального ОЗ).": "Every time creature attacks and damages another card, it heals itself by X HP\n                        (up to max HP).",
    "Перед нанесением урона накладывает сглаз на существо напротив, увеличивая следующий входящий по нему урон на +X.": "Before dealing damage, hexes the opposite creature, increasing next incoming damage by +X.",
    "В конце каждого хода испускает ядовитые споры, наносящие X чистого урона случайному живому человеку врага на поле.": "At the end of each turn, emits poisonous spores dealing X pure damage to a random living enemy on board.",
    "💡 Совет: Жертвуйте слабыми или ранеными картами для взрывного усиления ваших ключевых существ!": "💡 Tip: Sacrifice weak or wounded cards for explosive buffs to your key creatures!",
    "ПОНЯТНО, В БОЙ!": "UNDERSTOOD, TO BATTLE!",
    "Здоровье:": "Health:",
    "х": "turns",
    "Уничтожает союзника.": "Destroys an ally.",
    "Ходы ожидания атаки.": "Turns waiting to attack."
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("done")
